<?php

/**
 * @author  MEMORA solutions <info@memora.ca> (https://memora.solutions)
 *
 * @project memora/laravel-saas-boilerplate
 *
 * Breadcrumb labels — maps route segments to display labels.
 * Used by BreadcrumbService to auto-generate breadcrumbs from route names.
 */

declare(strict_types=1);

return [
    'labels' => [
        'blog' => 'Blog',
        'articles' => 'Articles',
        'pages' => 'Pages',
        'categories' => 'Catégories',
        'tags' => 'Tags',
        'media' => 'Médias',
        'faqs' => 'FAQ',
        'menus' => 'Menus',
        'testimonials' => 'Témoignages',
        'widgets' => 'Widgets',
        'custom-fields' => 'Champs personnalisés',
        'formbuilder' => 'Formulaires',
        'users' => 'Utilisateurs',
        'roles' => 'Rôles',
        'teams' => 'Équipes',
        'contacts' => 'Messages',
        'settings' => 'Paramètres',
        'branding' => 'Branding',
        'seo' => 'SEO',
        'redirects' => 'Redirections',
        'translations' => 'Traductions',
        'themes' => 'Thèmes',
        'cookie-categories' => 'Cookies',
        'backups' => 'Sauvegardes',
        'logs' => 'Journaux',
        'health' => 'Santé',
        'security' => 'Sécurité',
        'ecommerce' => 'Boutique',
        'products' => 'Produits',
        'orders' => 'Commandes',
        'coupons' => 'Coupons',
        'promotions' => 'Promotions',
        'shipping-zones' => 'Livraison',
        'saas' => 'SaaS',
        'plans' => 'Plans',
        'tenants' => 'Tenants',
        'booking' => 'Réservations',
        'appointments' => 'Rendez-vous',
        'services' => 'Services',
        'packages' => 'Forfaits',
        'gift-cards' => 'Cartes-cadeaux',
        'date-overrides' => 'Exceptions',
        'ai' => 'IA',
        'conversations' => 'Conversations',
        'knowledge' => 'Base connaissances',
        'tickets' => 'Tickets',
        'urls' => 'Sources URL',
        'analytics' => 'Analytics',
        'roadmap' => 'Roadmap',
        'boards' => 'Tableaux',
        'webhooks' => 'Webhooks',
        'notifications' => 'Notifications',
        'newsletter' => 'Newsletter',
        'campaigns' => 'Campagnes',
        'workflows' => 'Workflows',
        'templates' => 'Templates',
        'feature-flags' => 'Feature flags',
        'email-templates' => 'Templates email',
        'error-monitoring' => 'Erreurs',
        'activity-logs' => 'Activité',
        'failed-jobs' => 'Jobs échoués',
        'system-info' => 'Infos système',
        'onboarding' => 'Onboarding',
        'announcements' => 'Annonces',
        'experiments' => 'Expériences',
        'profile' => 'Profil',
        'create' => 'Créer',
        'edit' => 'Modifier',
        'show' => 'Détails',
        'index' => '',
        'dashboard' => 'Tableau de bord',
        'stats' => 'Statistiques',
    ],
];
