<?php

/**
 * Villes desservies par Kalystrat — pages-villes Local SEO 2026.
 * Référence : tendances GEO mai 2026 (pp_search) + plan d'affaire .plan_affaire/PLAN_ALI.txt.
 * Désactivable en commentant la route /zones-desservies/{slug} dans routes/web.php.
 */
return [
    'quebec' => [
        'slug'          => 'quebec',
        'nom'           => 'Québec',
        'nom_long'      => 'Ville de Québec',
        'region'        => 'Capitale-Nationale',
        'province'      => 'Québec',
        'meta_title'    => 'Construction Québec | Kalystrat – RBQ + 6 filiales',
        'meta_description' => 'Entrepreneur général à Québec avec 6 filiales spécialisées, accrédité RBQ. Projets résidentiels, commerciaux, patrimoniaux et multi-logements dans la Capitale-Nationale.',
        'h1'            => 'Entrepreneur général à Québec — Construction intégrée par Kalystrat',
        'intro_paragraph' => 'Située au cœur de la Capitale-Nationale, la ville de Québec comprend des arrondissements variés comme Beauport, Sainte-Foy, Sillery, Charlesbourg, La Cité-Limoilou et Les Rivières. Son climat rigoureux, marqué par des cycles de gel-dégel et d\'importantes accumulations de neige, impose des exigences techniques strictes en construction. Les sols argileux de Beauport ou le roc omniprésent à Charlesbourg représentent des défis géotechniques spécifiques. Kalystrat, entrepreneur général local, maîtrise ces contraintes grâce à son intégration verticale via ses six filiales spécialisées. Nous servons promoteurs résidentiels, entrepreneurs généraux, propriétaires, municipalités et investisseurs avec une approche « Conçu. Réalisé. Livré. » adaptée au tissu urbain et réglementaire québécois.',
        'arrondissements' => [
            'La Cité-Limoilou',
            'Sainte-Foy–Sillery–Cap-Rouge',
            'Beauport',
            'Charlesbourg',
            'Les Rivières',
            'La Haute-Saint-Charles',
        ],
        'projets_types' => [
            'Maison unifamiliale neuve',
            'Multi-logement résidentiel',
            'Rénovation patrimoniale (Vieux-Québec)',
            'Toiture après tempête hivernale',
            'Aménagement commercial',
        ],
        'reglementations' => [
            'Code de construction du Québec',
            'Régie du bâtiment du Québec (RBQ)',
            'Commission de la construction du Québec (CCQ)',
            'Règlements d\'urbanisme — Ville de Québec',
        ],
        'pourquoi_kalystrat' => [
            'Siège social local — équipes basées à Québec',
            'Connaissance fine des sols (argileux Beauport, roc Charlesbourg)',
            'Réseau RBQ + CCQ + APCHQ établi',
            'Intégration verticale six filiales — un seul interlocuteur',
        ],
        'lat'           => 46.8139,
        'lng'           => -71.2080,
        'population'    => 549459,
    ],
    'levis' => [
        'slug'          => 'levis',
        'nom'           => 'Lévis',
        'nom_long'      => 'Ville de Lévis',
        'region'        => 'Chaudière-Appalaches',
        'province'      => 'Québec',
        'meta_title'    => 'Entrepreneur général à Lévis | Kalystrat Construction',
        'meta_description' => 'Kalystrat, entrepreneur général à Lévis : maîtrise des sols variés et du climat rigoureux. Spécialisé en résidentiel, multi-logement et projets intégrés Chaudière-Appalaches.',
        'h1'            => 'Entrepreneur général à Lévis — Kalystrat',
        'intro_paragraph' => 'Située sur la rive sud du fleuve Saint-Laurent face à Québec, Lévis bénéficie d\'un développement urbain dynamique et d\'un marché immobilier en croissance. Son territoire, composé de secteurs aux sols variés (alluviaux près du fleuve, plus stables à l\'intérieur), exige une expertise géotechnique fine. Kalystrat y déploie son modèle d\'intégration verticale : conception, fondations adaptées, construction clé en main et coordination de six filiales spécialisées. La proximité immédiate avec Québec permet une logistique optimisée pour servir les promoteurs locaux, entrepreneurs généraux et particuliers exigeants de Chaudière-Appalaches.',
        'arrondissements' => [
            'Desjardins',
            'Lévis-Lauzon',
            'Saint-Romuald',
            'Pintendre',
            'Sainte-Hélène-de-Breakeyville',
        ],
        'projets_types' => [
            'Maisons unifamiliales haut de gamme',
            'Multi-logements résidentiels',
            'Rénovations majeures',
            'Développements résidentiels',
            'Bâtiments mixtes',
        ],
        'reglementations' => [
            'Plan d\'urbanisme et règlement de zonage de Lévis',
            'Code de construction du Québec',
            'Régie du bâtiment du Québec (RBQ)',
            'Commission de la construction du Québec (CCQ)',
        ],
        'pourquoi_kalystrat' => [
            'Proximité stratégique avec Québec — logistique optimisée',
            'Expertise sur sols hétérogènes (alluvions, sédiments)',
            'Capacité à livrer des projets clé en main',
            'Présence locale via filiales intégrées',
        ],
        'lat'           => 46.7378,
        'lng'           => -71.2354,
        'population'    => 149000,
    ],
    'sainte-foy' => [
        'slug'          => 'sainte-foy',
        'nom'           => 'Sainte-Foy',
        'nom_long'      => 'Sainte-Foy (Ville de Québec)',
        'region'        => 'Capitale-Nationale',
        'province'      => 'Québec',
        'meta_title'    => 'Entrepreneur général à Sainte-Foy | Kalystrat Québec',
        'meta_description' => 'À Sainte-Foy, Kalystrat réalise des projets résidentiels et commerciaux adaptés au marché universitaire et aux promoteurs de condos haut de gamme.',
        'h1'            => 'Entrepreneur général à Sainte-Foy — Kalystrat',
        'intro_paragraph' => 'Sainte-Foy, cœur économique et universitaire de la région de Québec, combine un fort potentiel résidentiel avec une demande croissante en logements modernes près de l\'Université Laval. Le sol, principalement limoneux avec poches argileuses, nécessite des fondations adaptées. Kalystrat y applique son approche d\'intégration verticale : conception, fondations, structure, enveloppe, finition coordonnées par ses six filiales. La zone attire des projets de densification urbaine où notre maîtrise des délais et des coûts fait la différence pour promoteurs immobiliers, investisseurs et particuliers.',
        'arrondissements' => [
            'Cité-Universitaire',
            'Le Plateau',
            'Saint-Louis',
            'Pointe-de-Sainte-Foy',
            'La Chanterelle',
        ],
        'projets_types' => [
            'Condos haut de gamme',
            'Immeubles à vocation étudiante',
            'Bureaux professionnels',
            'Maisons contemporaines',
            'Rénovations urbaines',
        ],
        'reglementations' => [
            'Règlement de zonage Ville de Québec (Sainte-Foy)',
            'Politique de densification urbaine',
            'Code de construction du Québec',
            'Règlements RBQ et CCQ',
        ],
        'pourquoi_kalystrat' => [
            'Maîtrise du marché étudiant et résidentiel premium',
            'Logistique optimisée depuis Québec',
            'Expérience en projets densifiés',
            'Intégration verticale six filiales',
        ],
        'lat'           => 46.7763,
        'lng'           => -71.2864,
        'population'    => 92000,
    ],
    'beauport' => [
        'slug'          => 'beauport',
        'nom'           => 'Beauport',
        'nom_long'      => 'Beauport (Ville de Québec)',
        'region'        => 'Capitale-Nationale',
        'province'      => 'Québec',
        'meta_title'    => 'Entrepreneur général à Beauport | Kalystrat Construction',
        'meta_description' => 'Kalystrat intervient à Beauport avec expertise sur sols argileux : maisons familiales, multi-logements et rénovations. Solutions clé en main pour secteur en expansion.',
        'h1'            => 'Entrepreneur général à Beauport — Kalystrat',
        'intro_paragraph' => 'Beauport, arrondissement familial de Québec, connaît une forte croissance démographique et une demande soutenue en maisons unifamiliales et petits multiplex. Les sols argileux dominants exigent des techniques de fondation renforcées, notamment contre le gonflement saisonnier dû au gel-dégel. Kalystrat y déploie ses équipes spécialisées et ses six filiales internes pour garantir stabilité structurelle, isolation optimale et finitions durables. Grâce à sa position stratégique entre l\'autoroute Félix-Leclerc et le centre-ville, Beauport profite d\'une accessibilité idéale exploitée pour une logistique efficace et des délais maîtrisés.',
        'arrondissements' => [
            'Beauport-Centre',
            'Villeneuve',
            'Montmorency',
            'La Plaine',
            'Plateau-Bellevue',
        ],
        'projets_types' => [
            'Maisons familiales',
            'Duplex et triplex',
            'Rénovations énergétiques',
            'Petits immeubles locatifs',
            'Aménagements extérieurs intégrés',
        ],
        'reglementations' => [
            'Règlement de zonage Beauport (Ville de Québec)',
            'Code de construction du Québec',
            'Normes RBQ pour sols argileux',
            'Règlements sur les eaux de ruissellement',
        ],
        'pourquoi_kalystrat' => [
            'Expertise spécifique aux sols argileux',
            'Offre complète pour familles en croissance',
            'Présence opérationnelle dans l\'est de Québec',
            'Capacité à gérer plusieurs chantiers simultanés',
        ],
        'lat'           => 46.8709,
        'lng'           => -71.1928,
        'population'    => 84000,
    ],
    'sillery' => [
        'slug'          => 'sillery',
        'nom'           => 'Sillery',
        'nom_long'      => 'Sillery (Ville de Québec)',
        'region'        => 'Capitale-Nationale',
        'province'      => 'Québec',
        'meta_title'    => 'Entrepreneur général à Sillery | Rénovation premium Kalystrat',
        'meta_description' => 'À Sillery, quartier patrimonial de Québec, Kalystrat excelle dans la rénovation de maisons centenaires et les constructions haut de gamme respectueuses du bâti existant.',
        'h1'            => 'Entrepreneur général à Sillery — Kalystrat',
        'intro_paragraph' => 'Niché sur les falaises du Saint-Laurent, Sillery est un quartier prestigieux marqué par un riche patrimoine architectural et des résidences centenaires. Le marché y privilégie la qualité, la discrétion et le respect du caractère historique. Kalystrat y déploie une approche sur mesure : diagnostic structurel précis, rénovations invisibles mais performantes (isolation, électricité, plomberie) et extensions harmonieuses. Nos six filiales spécialisées en finition fine et menuiserie sur mesure assurent une cohérence parfaite entre tradition et modernité, avec un suivi rigoureux et personnalisé.',
        'arrondissements' => [
            'Sillery-Village',
            'Bois-de-Coulonge',
            'Cap-Rouge Est',
            'Parc-de-la-Francophonie',
            'Côte-de-Sillery',
        ],
        'projets_types' => [
            'Rénovations patrimoniales',
            'Maisons de luxe neuves',
            'Agrandissements discrets',
            'Restauration de façades',
            'Aménagements intérieurs haut de gamme',
        ],
        'reglementations' => [
            'Règlement sur le patrimoine bâti — Ville de Québec',
            'Zonage résidentiel exclusif',
            'Normes de conservation patrimoniale',
            'Permis de démolition restreints',
        ],
        'pourquoi_kalystrat' => [
            'Sensibilité au patrimoine architectural',
            'Expertise en finitions sur mesure',
            'Discrétion et service client premium',
            'Accès rapide aux artisans spécialisés via nos filiales',
        ],
        'lat'           => 46.7768,
        'lng'           => -71.2555,
        'population'    => 12000,
    ],
];
